# This workflow will do a clean install of dependencies, and compile the typescript.

name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v6

      - name: Install mise
        uses: jdx/mise-action@v3.5.1

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Package
        run: npm pack

      - name: Prepare Build Artifact
        id: before_deploy
        shell: bash
        run: |
          export FILE_NAME=(*.tgz)
          echo "file_name=${FILE_NAME}" >> "$GITHUB_OUTPUT"
      - name: Store Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.os }}-${{ steps.before_deploy.outputs.file_name }}
          path: ${{ steps.before_deploy.outputs.file_name }}
