/**
 * Copyright (c) 2020-2026 Vex Heavy Industries LLC
 * Licensed under AGPL-3.0. See LICENSE for details.
 * Commercial licenses available at vex.wtf
 */

export {
    ActionTokenSchema,
    AuthorizedMsgSchema,
    BaseMsgSchema,
    ChallMsgSchema,
    ChannelSchema,
    datetime,
    DevicePayloadSchema,
    DeviceSchema,
    EmojiSchema,
    ErrMsgSchema,
    FilePayloadSchema,
    FileResponseSchema,
    FileSQLSchema,
    IdentityKeysSchema,
    InviteSchema,
    KeyBundleSchema,
    MailSQLSchema,
    MailType,
    MailWSSchema,
    NotifyMsgSchema,
    PasskeyAuthFinishPayloadSchema,
    PasskeyAuthStartPayloadSchema,
    PasskeyRegistrationFinishPayloadSchema,
    PasskeyRegistrationStartPayloadSchema,
    PasskeySchema,
    PermissionSchema,
    PingMsgSchema,
    PongMsgSchema,
    PreKeysSQLSchema,
    PreKeysWSSchema,
    RatchetHeaderSchema,
    ReceiptMsgSchema,
    RegistrationPayloadSchema,
    ResourceMsgSchema,
    RespMsgSchema,
    ServerSchema,
    SessionSQLSchema,
    SocketAuthErrors,
    SuccessMsgSchema,
    TokenScopes,
    UnauthorizedMsgSchema,
    UserRecordSchema,
    UserSchema,
    WSMessageSchema,
} from "./schemas/index.js";

// Types (interfaces — source of truth)
export type {
    ActionToken,
    AuthorizedMsg,
    BaseMsg,
    ChallMsg,
    Channel,
    ClientMessage,
    Device,
    DevicePayload,
    Emoji,
    ErrMsg,
    FilePayload,
    FileResponse,
    FileSQL,
    IdentityKeys,
    Invite,
    KeyBundle,
    KeyBundleEntry,
    MailSQL,
    MailWS,
    NotifyMsg,
    Passkey,
    PasskeyAuthenticationOptions,
    PasskeyRegistrationOptions,
    Permission,
    PingMsg,
    PongMsg,
    PreKeysSQL,
    PreKeysWS,
    PublicKeyCredentialCreationOptionsJSON,
    PublicKeyCredentialDescriptorJSON,
    PublicKeyCredentialRequestOptionsJSON,
    RatchetHeader,
    ReceiptMsg,
    RegistrationPayload,
    ResourceMsg,
    RespMsg,
    Server,
    SessionSQL,
    SuccessMsg,
    UnauthorizedMsg,
    User,
    UserRecord,
    WSMessage,
} from "./schemas/index.js";
